### ISSUE TITLE
Interval inclusiveness like PostgreSQL Temporal period type

### ISSUE THREAD

**Issue by jfkw** [aredington/monotony#3]
Hello Alex,

```[#<Date Sat Jan 01 00:00:00 EST 2011> #<Date Sat Dec 31 23:59:59 EST 2011>]

``````

Have you considered inclusive and exclusive boundaries to capture the time outside the 1-second quantization?

An example is the PostgreSQL Temporal Extension period type:

 ```select period('2011-01-01 00:00:00-08', '2012-01-01 00:00:00-08');                                                                                  
                      period                      
    --------------------------------------------------
      [2011-01-01 00:00:00-08, 2012-01-01 00:00:00-08)
``````

This particular text representation is not appropriate for lisp, but the functionality seems like a good fit for monotony.

http://temporal.projects.postgresql.org/reference.html

Paraphrasing:

"The period text representation is one of the following forms:

```( timestamptz, timestamptz )
  [ timestamptz, timestamptz )
  ( timestamptz, timestamptz ]
  [ timestamptz, timestamptz ]

```

"Where timestamptz is a valid representation of a timestamptz. The choice of brackets represents the inclusiveness of the interval. A square bracket makes that side inclusive, and a peren makes that side exclusive.

Thanks,
Jeff
```

**Comment by aredington** [comment]
Jeff,

What exactly do you think would be the use case for something like this? 

The example output in the readme uses a vector of pairs of inclusive timestamps to represent a range of time, and the presentation is a function of Clojure's literal syntax for vectors (which begin and end with [])

As monotony is a Clojure library, the semantic meaning of square brackets and parenthesis are functions of the language (specifically, to indicate a vector literal and a list literal). Mixing and matching them would be a language level syntactic error, so I'm not sure I understand the specific request? Maybe some functions which accept two end points and generate a correct vector representing the period of time between them?
